FROM {{ image_spec("openstack-base") }}
MAINTAINER {{ maintainer }}

{{ copy_sources("openstack/heat", "/heat") }}

RUN useradd --user-group heat \
    && /var/lib/microservices/venv/bin/pip install /heat \
    && mkdir -p /var/lib/heat /etc/heat \
    && chown -R heat: /var/lib/heat /etc/heat \
    && cp -r /heat/etc/heat/* /etc/heat \
    && usermod -a -G microservices heat
